<?xml version="1.0"?>
<robot name="qube_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Globale materialer -->
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Makro-parametre -->
  <xacro:property name="base_length" value="1" />
  <xacro:property name="base_width" value="1" />
  <xacro:property name="base_height" value="1" />
  <xacro:property name="disk_radius" value="0.5" />
  <xacro:property name="disk_height" value="0.2" />
  <xacro:property name="pointer_length" value="0.4" />
  <xacro:property name="pointer_radius" value="0.05" />

  <xacro:macro name="qube">
    <!-- Base -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
      </inertial>
    </link>

    <!-- Roterende disk -->
    <link name="rotating_disk">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${disk_radius}" length="${disk_height}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.05" iyz="0" izz="0.05"/>
      </inertial>
    </link>

    <joint name="disk_joint" type="continuous">
      <parent link="base_link"/>
      <child link="rotating_disk"/>
      <origin xyz="0 0 ${base_height/2 + disk_height/2}"/>
      <axis xyz="0 0 1"/>
    </joint>

    <!-- Hvit viser -->
    <link name="pointer">
      <visual>
        <origin xyz="0 0 0" rpy="0 1.5708 0"/> <!-- Roter 90Â° om Y-aksen -->
        <geometry>
          <cylinder radius="${pointer_radius}" length="${pointer_length}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
    </link>

    <joint name="pointer_joint" type="fixed">
      <parent link="rotating_disk"/>
      <child link="pointer"/>
      <origin xyz="${disk_radius} 0 0"/> <!-- Plasser ytterkant av disk -->
    </joint>
  </xacro:macro>
</robot>