<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Macro-parametre -->
  <xacro:property name="base_length" value="0.1" />
  <xacro:property name="base_width" value="0.1" />
  <xacro:property name="base_height" value="0.1" />
  <xacro:property name="disk_radius" value="0.05" />
  <xacro:property name="disk_height" value="0.02" />
  <xacro:property name="pointer_length" value="0.04" />
  <xacro:property name="pointer_radius" value="0.005" />

  <xacro:macro name="qube">
    <!-- Base -->
    <link name="base_link">
      <visual>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
    </link>

    <!-- Roterende disk -->
    <link name="rotating_disk">
      <visual>
        <geometry>
          <cylinder radius="${disk_radius}" length="${disk_height}"/>
        </geometry>
        <material name="red">
          <color rgba="1 0 0 1"/>
        </material>
      </visual>
    </link>

    <joint name="disk_joint" type="continuous">
      <parent link="base_link"/>
      <child link="rotating_disk"/>
      <origin xyz="0 0 ${base_height/2 + disk_height/2}"/>
      <axis xyz="0 0 1"/>
    </joint>

    <!-- Hvit viser -->
    <link name="pointer">
      <visual>
        <geometry>
          <cylinder radius="${pointer_radius}" length="${pointer_length}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
    </link>

    <joint name="pointer_joint" type="fixed">
      <parent link="rotating_disk"/>
      <child link="pointer"/>
      <origin xyz="${disk_radius - pointer_length/2} 0 0"/>
    </joint>
  </xacro:macro>
</robot>
